spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
