-- H2 쿼리입니다.
-- MYSQL 에서 사용 시 일부 쿼리 수정이 필요합니다.

DROP TABLE if EXISTS member CASCADE;
CREATE TABLE member (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS flight_information;
CREATE TABLE flight_information (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    flight_no VARCHAR(20),
    departure_time VARCHAR(20),
    arrival_time VARCHAR(20),
    PRIMARY KEY (id)
);
INSERT INTO flight_information (flight_no, departure_time,arrival_time) VALUES ('KE123', '2024-01-01', '2024-02-03');
INSERT INTO flight_information (flight_no, departure_time,arrival_time) VALUES ('OZ998', '2024-03-01', '2024-03-03');
INSERT INTO flight_information (flight_no, departure_time,arrival_time) VALUES ('JJ123', '2024-04-01', '2024-04-03');
INSERT INTO flight_information (flight_no, departure_time,arrival_time) VALUES ('NU555', '2024-05-01', '2024-05-03');